### ISSUE TITLE
Implementing JSON

### ISSUE THREAD

**Issue by f-f** [purescm/purescript-core#8]
We already have `json` in tree, and the FFI surface is not large - we mostly need a `JSON.parse` and a `JSON.print`.

We have a few choices - one is to have the parser in pure scheme, e.g. [porting this](https://github.com/iovxw/chez-json/blob/master/json/parser.scm) to our string implementation.

Another possibility (and what I'd prefer since it's likely to be more performant) is to bind to [simdjson](https://github.com/simdjson/simdjson), a fast SIMD parser, which is what nodejs uses under the hood as well.
Looking at [the tutorial](https://github.com/simdjson/simdjson/blob/master/doc/basics.md#the-basics-loading-and-parsing-json-documents), the API seems straightforward - since it's C++ we'd need a small wrapper to expose a C interface, but fortunately [we can reuse this from some other binding](https://github.com/velveteer/hermes/blob/master/cbits/lib.cpp) (see [here](https://github.com/velveteer/hermes/blob/master/src/Data/Hermes/SIMDJSON/Bindings.hs) for the types).

**Comment by anttih** [comment]
Closing this as we have `json` now implemented in scheme. Maybe we'll later make it faster by using simdjson bindings.
